samples: config/samples.tsv
results_dir: results
metadata_dir: results/metadata
busco_lineage: solanales_odb12
busco_download_path: work/busco_downloads
occupancy_threshold: 0.8
sequence_type: protein
alignment_tool: mafft
trimming_mode: none
gene_tree_tool: iqtree3
species_tree_backend: wastral
threads:
  default: 4
  alignment: 1
  busco: 4
  iqtree: 4
